### PR TITLE
Changed url of libssl in dockerfile

### PR DESCRIPTION
**Pull request by mlrdk**

### CODE REVIEW

**Comment by nanxstats** [comment]
Hi @mlrdk , thanks for the patch --- this is really nice! However, we have decided to rewrite this completely with a more general solution instead of installing specific versions of libssl. We expect to deliver the new Dockerfile soon.

**Comment by mlrdk** [comment]
@road2stat no problem. If it's no problem, I could take the task of writing the new dockerfile, since I agree that this one is really specific and a little bit outdated.

**Comment by nanxstats** [comment]
Hi Milorad @mlrdk , -- this should be fixed by https://github.com/sbg/sevenbridges-r/commit/50411f75171ebec6743f4b07d0ef3c300758ce06. Could you please take some time to test and see if the image works as expected? From my test it seems we could remove the libssl part safely.

**Comment by mlrdk** [comment]
@road2stat Sure thing, will get back to you here with updates!

**Comment by mlrdk** [comment]
Update 

-The image works, and the shiny server is up and running!

**Comment by nanxstats** [comment]
@mlrdk -- great! Thank a lot for testing this out.
We will probably roll out a new release to Bioconductor this weekend, with this fix and other improvements.

**Pull request closed without merging**
